name: Build mimic (static x86_64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest

    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y \
          git \
          build-essential \
          clang \
          cmake \
          libssl-dev \
          zlib1g-dev \
          libc6-dev \
          file

    - name: Build ptrace_do (static)
      run: |
        git clone https://github.com/emptymonkey/ptrace_do.git
        cd ptrace_do
        make CC="gcc -static" CFLAGS="-std=gnu99 -Wall -Wextra -pedantic -O3" LDFLAGS="-static"
        cd ..

    - name: Build mimic (static)
      run: |
        git clone https://github.com/emptymonkey/mimic.git
        cd mimic
        make CC="gcc -static" CFLAGS="-static" LDFLAGS="-static"

    - name: Verify static linking
      run: |
        file mimic/mimic
        ldd mimic/mimic || echo "Static binary (as expected)"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mimic-static-x86_64
        path: mimic/mimic
        if-no-files-found: error
