name: Build mimic with musl (static x86_64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest  # 使用Alpine容器获得musl工具链

    steps:
    - name: Clone repository
      run: |
        apk add --no-cache git  # 安装git
        git clone https://github.com/emptymonkey/ptrace_do.git
        git clone https://github.com/emptymonkey/mimic.git

    - name: Install build dependencies
      run: |
        apk add --no-cache \
          build-base \
          clang \
          cmake \
          linux-headers \
          musl-dev \
          openssl-dev

    - name: Build mimic (static with musl)
      run: |
        cd ptrace_do
        make
        cd ..
        cd mimic
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mimic-static-x86_64
        path: mimic/mimic  # 二进制路径
        if-no-files-found: error
