name: Build mimic with musl (static x86_64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest  # 改用Ubuntu以获取glibc

    steps:
    - name: Clone repository
      run: |
        apt-get update && apt-get install -y git

    - name: Install build dependencies
      run: |
        apt-get install -y \
          build-essential \
          clang \
          cmake \
          libssl-dev

    - name: Build mimic (static with musl)
      run: |
        git clone https://github.com/emptymonkey/ptrace_do.git
        cd ptrace_do
        make
        cd ..
        
        git clone https://github.com/emptymonkey/mimic.git
        cd mimic
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mimic-static-x86_64
        path: mimic/mimic  # 二进制路径
        if-no-files-found: error
